import random

class HeuristicsConstants:

	# RELATEDNESS MEASURE
	FROM_NODE_WEIGHT = 0.005
	TO_NODE_WEIGHT = 0.005
	IS_CHARGING_WEIGHT = 0.315
	TRAVEL_DISTANCE_WEIGHT = 0.005
	START_TIME_WEIGHT = 0.05

	# REWARDS
	BEST = 33.0
	BETTER = 9.0
	ACCEPTED = 13.0

	# DETERMINISM PARAMETER
	DETERMINISM_PARAMETER_WORST = 10
	DETERMINISM_PARAMETER_RELATED = 10
	DETERMINISM_PARAMETER_GREEDY = 10


	# ADAPTIVE WEIGHT LOWER THRESHOLD
	LOWER_THRESHOLD = 0.2

	# DESTROY/REPAIR FACTOR q hat
	DESTROY_REPAIR_FACTOR = (0.15, 0.50)
	#DESTROY_REPAIR_FACTOR = (0.10, 0.40)

	# REWARD DECAY PARAMETER / REACTION FACTOR
	REWARD_DECAY_PARAMETER = 0.1

	# ITERATIONS
	ITERATIONS_ALNS = 1
	ITERATIONS_SEGMENT = 50
	TIME_LIMIT = 600
	FIRST_CHECKPOINT = 200
	SECOND_CHECKPOINT = 400

	# AN ACCEPTANCE PERCENTAGE OF 2 MEANS ALL CAR MOVES ARE INCLUDED
	ACCEPTANCE_PERCENTAGE = 2.0
	DISTANCE_INCLUSION_FACTOR = 1

	PLANNING_PERIOD = 60
	#NUM_FIRST_STAGE_TASKS = 2


	@staticmethod
	def set_acceptance_percentage(val):
		HeuristicsConstants.ACCEPTANCE_PERCENTAGE = val