### CONSTANTS ####

#BOARD SIZE - DONT CHANGE
board:
  operating_area_grid:
    x: 15
    y: 8
  coordinates:
    lower_left:
      lat: 59.904574
      long: 10.640726
    upper_right:
      lat: 59.962019
      long: 10.855535

#CHARGING NODES
charging_nodes:
  num_charging: 2
  parking_nodes: [1, 2]
  capacities: [2, 2]
  max_capacities: [2, 2]

#EMPLOYEES
employees:
  num_employees: 2
  start_time: [0, 5]
  occupied: [0, 1]

#NODE STATE
# This must be replaced by estimates derived from vy data
node_states:
  # probability of a charging node having 0 cars is 0.75, 1 car 0.25
  charging:
    0: 0.75
    1: 0.25
  parking:
    0: 0.425
    2: 0.15
    3: 0.425
  ideal:
    0: 0.4
    1: 0.05
    2: 0.4
    3: 0.15

# DEMANDS
node_demands:
  customer_requests:
    0: 0.25
    1: 0.5
    2: 0.25
  car_returns:
    0: 0.25
    1: 0.5
    2: 0.25

# HANDLING TIME
time_constants:
  handling_parking: 4
  handling_charging: 5
  planning_period: 60

#OBJECTIVE FUNCTION
objective_function:
  profit_rental: 40.5
  cost_relocation: 0.42
  cost_deviation: 28.35
  cost_deviation_charging: 40.5