### CONSTANTS ####

# NUMBER OF EXAMPLES TO CREATE #
examples: 3

#BOARD SIZE - DONT CHANGE
board_size:
  operating_area_size:
    x: 15
    y: 8

parking_nodes:
    num_parking: 6

#CHARGING NODES
charging_nodes:
  num_charging: 2 #vurder fjern
  parking_nodes: [1, 2]
  capacities: [2, 2]
  max_capacities: [2, 2]

#EMPLOYEES
employees:
  num_employees: 2
  start_time: [0, 5]
  occupied: [0, 1]

#NODE STATE
# This must be replaced by estimates derived from vy data
node_states:
  # probability of a charging node having 0 cars is 0.75, 1 car 0.25
  charging:
    0: 0.75
    1: 0.25
  parking:
    0: 0.425
    2: 0.15
    3: 0.425

#DEMANDS
node_demands:
  ideal:
    0: 0.4
    1: 0.05
    2: 0.4
    3: 0.15
  customer_requests:
    0: 0.25
    1: 0.5
    2: 0.25
  car_returns:
    0: 0.25
    1: 0.5
    2: 0.25

#OBJECTIVE FUNCTION
objective_function:
  profit_rental: 40.5
  cost_relocation: 0.42
  cost_deviation: 28.35