### INSTANCE ###

#TIME OF DAY
time_of_day: 16

# NUMBER OF EXAMPLES TO CREATE #
examples: 1

# SCENARIOS
num_scenarios: 2

# TASKS
tasks:
  num_all: 4
  num_first_stage: 1

# NUMBER OF PARKING NODES IN INSTANCE
num_parking_nodes: 2

# NUMBER OF AVAILABLE/CHARGED CARS IN INSTANCE
num_charged_cars: 3

#CHARGING NODES
charging_nodes:
  num_charging: 1
  parking_nodes: [2]
  capacities: [2]

#EMPLOYEES
employees:
  num_employees: 1
  start_time: [0]
  handling: [0]

planning_period: 60

