### CONSTANTS ####

# NUMBER OF EXAMPLES TO CREATE #
examples: 1

# SCENARIOS
num_scenarios: 3

# TASKS
tasks:
  num_all: 4
  num_first_stage: 2

#BOARD SIZE - DONT CHANGE
board:
  parking_node_dim:
    x: 3
    y: 2

#CHARGING NODES
charging_nodes:
  num_charging: 2
  parking_nodes: [1, 2]
  capacities: [2, 2]
  max_capacities: [2, 2]

#EMPLOYEES
employees:
  num_employees: 4
  start_time: [0, 5, 0, 0]
  handling: [0, 0, 0, 0]