### INSTANCE ###

#TIME OF DAY
time_of_day: 16

# NUMBER OF EXAMPLES TO CREATE #
examples: 1

# SCENARIOS
num_scenarios: 25

# TASKS
tasks:
  num_all: 4
  num_first_stage: 2

# NUMBER OF PARKING NODES IN INSTANCE
num_parking_nodes: 50

# NUMBER OF AVAILABLE/CHARGED CARS IN INSTANCE
num_charged_cars: 40

#CHARGING NODES
charging_nodes:
  num_charging: 5
  parking_nodes: [2,10,20,30,40]
  capacities: [2,2,2,2,2]

#EMPLOYEES
employees:
  num_employees: 6
  start_time: [0,0,0,0,0,0]
  handling: [0,0,0,0,0,0]

planning_period: 60

