### INSTANCE ###

#TIME OF DAY
time_of_day: 16

# NUMBER OF EXAMPLES TO CREATE #
examples: 1

# SCENARIOS
num_scenarios: 25

# TASKS
tasks:
  num_all: 4
  num_first_stage: 2

# NUMBER OF PARKING NODES IN INSTANCE
num_parking_nodes: 150

# NUMBER OF AVAILABLE/CHARGED CARS IN INSTANCE
num_charged_cars: 120

#CHARGING NODES
charging_nodes:
  num_charging: 15
  parking_nodes: [7,12,26,35,47,55,69,72,84,93,101,120,128,133,144]
  capacities: [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2]

#EMPLOYEES
employees:
  num_employees: 12
  start_time: [4, 2, 8, 6, 8, 8, 6, 0, 9, 3, 7, 10] #, [1, 4, 10, 9, 5, 7]
  handling: [0,0,0,0,0,0,0,0,0,0,0,0]

planning_period: 60

