### INSTANCE ###

#TIME OF DAY
time_of_day: 16

# NUMBER OF EXAMPLES TO CREATE #
examples: 1

# SCENARIOS
num_scenarios: 50

# TASKS
tasks:
  num_all: 4
  num_first_stage: 2

# NUMBER OF PARKING NODES IN INSTANCE
num_parking_nodes: 70

# NUMBER OF AVAILABLE/CHARGED CARS IN INSTANCE
num_charged_cars: 80

#CHARGING NODES
charging_nodes:
  num_charging: 8
  parking_nodes: [1,4,8,12,15,26,47,49]
  capacities: [2,2,2,2,2,2,2,2]

#EMPLOYEES
employees:
  num_employees: 12
  start_time: [0,0,0,0,0,0,0,0,0,0,0,0]
  handling: [0,0,0,0,0,0,0,0,0,0,0,0]

planning_period: 60

