### INSTANCE ###

#TIME OF DAY
time_of_day: 8

# NUMBER OF EXAMPLES TO CREATE #
examples: 1

# SCENARIOS
num_scenarios: 2

# TASKS
tasks:
  num_all: 4
  num_first_stage: 2

# NUMBER OF PARKING NODES IN INSTANCE
num_parking_nodes: 25

# NUMBER OF CHARGED CARS IN INSTANCE
num_charged_cars: 15

#CHARGING NODES
charging_nodes:
  num_charging: 2
  parking_nodes: [5,12]
  capacities: [2,2]

#EMPLOYEES
employees:
  num_employees: 4
  start_time: [0,0,0,0]
  handling: [0,0,0,0]

planning_period: 60

