### INSTANCE ###

#TIME OF DAY
time_of_day: 16

# NUMBER OF EXAMPLES TO CREATE #
examples: 1

# SCENARIOS
num_scenarios: 25

# TASKS
tasks:
  num_all: 4
  num_first_stage: 2

# NUMBER OF PARKING NODES IN INSTANCE
num_parking_nodes: 20

# NUMBER OF AVAILABLE/CHARGED CARS IN INSTANCE
num_charged_cars: 20

#CHARGING NODES
charging_nodes:
  num_charging: 4
  parking_nodes: [1,4,8,19]
  capacities: [2,2,2,2]

#EMPLOYEES
employees:
  num_employees: 4
  start_time: [0,0,0,0]
  handling: [0,0,0,0]

planning_period: 60

