### INSTANCE ###

#TIME OF DAY
time_of_day: 16

# NUMBER OF EXAMPLES TO CREATE #
examples: 1

# SCENARIOS
num_scenarios: 25

# TASKS
tasks:
  num_all: 4
  num_first_stage: 2

# NUMBER OF PARKING NODES IN INSTANCE
num_parking_nodes: 15

# NUMBER OF AVAILABLE/CHARGED CARS IN INSTANCE
num_charged_cars: 12

#CHARGING NODES
charging_nodes:
  num_charging: 2
  parking_nodes: [5, 12]
  capacities: [2, 2]

#EMPLOYEES
employees:
  num_employees: 4
  start_time: [0, 2, 5, 5] # [1, 5, 9, 5], [7, 8, 1, 0]
  handling: [0,0,0,0]

planning_period: 60

