### INSTANCE ###

#TIME OF DAY
time_of_day: 7

# NUMBER OF EXAMPLES TO CREATE #
examples: 1

# SCENARIOS
num_scenarios: 10

# TASKS
tasks:
  num_all: 5
  num_first_stage: 1

# NUMBER OF PARKING NODES IN INSTANCE
num_parking_nodes: 14

# NUMBER OF CHARGED CARS IN INSTANCE
num_charged_cars: 13

#CHARGING NODES
charging_nodes:
  num_charging: 2
  parking_nodes: [3,12]
  capacities: [2,2]

#EMPLOYEES
employees:
  num_employees: 3
  start_time: [0,0,0]
  handling: [0,0,0]

planning_period: 60

