### INSTANCE ###

#TIME OF DAY
time_of_day: 16

# NUMBER OF EXAMPLES TO CREATE #
examples: 1

# SCENARIOS
num_scenarios: 25

# TASKS
tasks:
  num_all: 4
  num_first_stage: 2

# NUMBER OF PARKING NODES IN INSTANCE
num_parking_nodes: 30

# NUMBER OF AVAILABLE/CHARGED CARS IN INSTANCE
num_charged_cars: 24

#CHARGING NODES
charging_nodes:
  num_charging: 3
  parking_nodes: [1,12,26]
  capacities: [2,2,2]

#EMPLOYEES
employees:
  num_employees: 6
  start_time: [0, 3, 8, 3, 2, 10] # [10, 0, 8, 9, 10, 6], [8, 4, 7, 2, 8, 1]
  handling: [0,0,0,0,0,0]

planning_period: 60

