### INSTANCE ###

#TIME OF DAY
time_of_day: 16

# NUMBER OF EXAMPLES TO CREATE #
examples: 1

# SCENARIOS
num_scenarios: 1

# TASKS
tasks:
  num_all: 4
  num_first_stage: 4

# NUMBER OF PARKING NODES IN INSTANCE
num_parking_nodes: 30

# NUMBER OF AVAILABLE/CHARGED CARS IN INSTANCE
num_charged_cars: 20

#CHARGING NODES
charging_nodes:
  num_charging: 5
  parking_nodes: [3,5,10,12,30]
  capacities: [2,2,2,2,2]

#EMPLOYEES
employees:
  num_employees: 5
  start_time: [0,0,0,0,0]
  handling: [0,0,0,0,0]

planning_period: 60

