### INSTANCE ###

#TIME OF DAY
time_of_day: 16

# NUMBER OF EXAMPLES TO CREATE #
examples: 1

# SCENARIOS
num_scenarios: 2

# TASKS
tasks:
  num_all: 4
  num_first_stage: 1

# NUMBER OF PARKING NODES IN INSTANCE
num_parking_nodes: 10

# NUMBER OF AVAILABLE/CHARGED CARS IN INSTANCE
num_charged_cars: 20

#CHARGING NODES
charging_nodes:
  num_charging: 3
  parking_nodes: [3,5,9]
  capacities: [2,2,2]

#EMPLOYEES
employees:
  num_employees: 1
  start_time: [0]
  handling: [0]

planning_period: 60

