### INSTANCE ###

#TIME OF DAY
time_of_day: 16

# NUMBER OF EXAMPLES TO CREATE #
examples: 1

# SCENARIOS
num_scenarios: 25

# TASKS
tasks:
  num_all: 4
  num_first_stage: 2

# NUMBER OF PARKING NODES IN INSTANCE
num_parking_nodes: 10

# NUMBER OF AVAILABLE/CHARGED CARS IN INSTANCE
num_charged_cars: 8

#CHARGING NODES
charging_nodes:
  num_charging: 1
  parking_nodes: [7]
  capacities: [2]

#EMPLOYEES
employees:
  num_employees: 2
  start_time: [5,9] # [10, 0], [10, 6]
  handling: [0,0]

planning_period: 60

